### ISSUE TITLE
刷新缓存和绑定公会能否支持艾特群友

### ISSUE THREAD

**Issue by MiroticLAM** [SonderXiaoming/kanna_connection_redive#1]
装上插件后再次感受到了群友清澈的愚蠢，只能来问问大佬。。
刷新缓存似乎是考虑到顶号问题，可群友又懒又蠢也没办法上他们的QQ，所以想问问能否增加管理员或超管权限去艾特群友使用刷新缓存和绑定公会的指令？

**Comment by SonderXiaoming** [comment]
如果你不查box，绑定公会其实没啥必要，至于刷新确实可能顶号

**Comment by SonderXiaoming** [comment]
`    for m in ev.message:
        if m.type == 'at' and m.data['qq'] != 'all':
            return int(m.data['qq'])`
这段代码是获取at，自行修改

**Comment by MiroticLAM** [comment]
OK，感谢大佬
