### ISSUE TITLE
有没有办法改成自动过码失败后，进行群里手动过码？有时候人多上不去

### ISSUE THREAD

**Issue by duoshoumiao** [SonderXiaoming/kanna_connection_redive#12]
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/94856184/a6d5c02f-9ec4-44c2-b6e7-bf697181d377)

**Comment by duoshoumiao** [comment]
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/94856184/7c2df80d-daf5-49ee-ae72-acfc244cb986)
救救

**Comment by SonderXiaoming** [comment]
手动过码可以看怡宝的方案
