### ISSUE TITLE
生成当前战报时，convert2img.py 中的 font.getsize(table[i][j])[0] 语句执行后 hoshinoBot 闪退

### ISSUE THREAD

**Issue by HHEBL** [SonderXiaoming/kanna_connection_redive#15]
如题，发现在群里发送“当前战报”后hoshinoBot会闪退，经排查后发现是在convert2img插件里，一执行 font.getsize(...) 就会闪退，如果全部用固定数值代替的话，最后可以生成一个全是框的图片。打印了一下table里的内容，应该也是正常的。求大佬解答一下这是怎么回事，谢谢！
table里的内容：
![table输出](https://github.com/SonderXiaoming/kanna_connection_redive/assets/64397778/4af0f514-a114-4d44-b06a-af61d0e3ea63)

用固定数值代替后输出结果：
![QQ图片20231225104636](https://github.com/SonderXiaoming/kanna_connection_redive/assets/64397778/8bcc64f4-c08c-4081-b9cb-a1be813ec101)

**Comment by SonderXiaoming** [comment]
需要降级pil版本

**Comment by SonderXiaoming** [comment]
当然，你也可以查一下pil文档看看getsize变成了什么。我目前没空修这个

**Comment by HHEBL** [comment]
好的谢谢，我去尝试一下

**Comment by HHEBL** [comment]
降级pillow库到6.2.1后问题解决。
