### ISSUE TITLE
绑定失败

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/kanna_connection_redive#2]
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/45947734/df9dca38-3e6e-458f-9e80-438fb0d9b684)
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/45947734/d86e18b2-7194-405b-9e93-c31bd86f484a)

**Comment by SonderXiaoming** [comment]
新建个data文件夹在kanna_connection_redive里面，再在里面新建个account文件夹

**Comment by 1529960009** [comment]
已解决
