### ISSUE TITLE
查助战功能能看公会战的ex装备吗

### ISSUE THREAD

**Issue by Momona0v0** [SonderXiaoming/kanna_connection_redive#21]
如题。

**Comment by SonderXiaoming** [comment]
争取这两天

**Comment by SonderXiaoming** [comment]
已更新，试试，效果图在readme

**Comment by Momona0v0** [comment]
谢谢大佬

**Comment by Momona0v0** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\qqbot\\HoshinoBot-master\\hoshino\\modules\\kanna_connection_redive\\img\\support_query\\template.jpg'
似乎是漏了一个模板图的样子？
