### ISSUE TITLE
战报bug

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/kanna_connection_redive#4]
![F2W~DQ$68}%(4N7W$D0HE$T](https://github.com/SonderXiaoming/kanna_connection_redive/assets/45947734/e77e01fc-2405-4d48-bf7c-34f0916b9a8b)

**Comment by SonderXiaoming** [comment]
pip install Pillow==9.5.0 pil库降级

**Comment by SonderXiaoming** [comment]
当然最好是有人pr新方法
