### ISSUE TITLE
【建议】出刀监控可以被艾特触发

### ISSUE THREAD

**Issue by 1529960009** [SonderXiaoming/kanna_connection_redive#5]
现在重启机器人，每个群的监控账户不会自动登录，导致不能实时汇报。
建议给机器人管理增加权限，直接艾特就能登录账户

**Comment by SonderXiaoming** [comment]
实际上有这两个指令，重启前搞一下就行了
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/98363578/bf045ec2-c3a2-47ee-a19c-fd3b84c5baf1)

**Comment by 1529960009** [comment]
![image](https://github.com/SonderXiaoming/kanna_connection_redive/assets/45947734/ad86f0b8-5c71-4341-b4d8-ef220b713604)
,重启前运行了缓存运行群，重启后无法自动登录

**Comment by 1529960009** [comment]
现在出刀+艾特可以正常触发

**Comment by 1529960009** [comment]
![Screenshot_2024-04-26-02-47-49-74_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/SonderXiaoming/kanna_connection_redive/assets/45947734/66f15eae-475e-424f-8389-c9df56a9b5ed)

艾特出刀监控,非本人无法触发,并弹不出权限不足提示

**Comment by SonderXiaoming** [comment]
qq at后会自动加个空格，把空格删掉就行了。或者你把那个指令改成prefix
